// Code generated by goctl. DO NOT EDIT.
package types

type NotifyReq struct {
	Chat_id string `path:"chat_id"`
	Text    string `json:"text"`
}

type NotifyResp struct {
	Status string `json:"status"`
}
